# Generated by Django 3.2.7 on 2021-10-07 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='標題')),
                ('image', models.ImageField(default=None, null=True, upload_to=shop.models.path_and_rename, verbose_name='圖片')),
            ],
            options={
                'verbose_name': '產品類別',
                'verbose_name_plural': '產品類別',
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='小計')),
            ],
            options={
                'verbose_name': '訂單產品',
                'verbose_name_plural': '訂單產品',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='標題')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('primary_image', models.ImageField(default=None, null=True, upload_to=shop.models.path_and_rename, verbose_name='主要圖片')),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='原價')),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='特價')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='產品類別')),
            ],
            options={
                'verbose_name': '產品',
                'verbose_name_plural': '產品',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立於')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新於')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='特價')),
                ('status', models.CharField(blank=True, max_length=63, null=True, verbose_name='訂單狀態')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='客戶')),
                ('products', models.ManyToManyField(related_name='orders', through='shop.Mapping', to='shop.Product', verbose_name='訂單內容')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
            },
        ),
        migrations.AddField(
            model_name='mapping',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='訂單'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='產品'),
        ),
    ]
