# Generated by Django 3.2.7 on 2021-10-07 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20211002_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '產品類別', 'verbose_name_plural': '產品類別'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '產品', 'verbose_name_plural': '產品'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=shop.models.path_and_rename, verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=63, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='產品類別'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='特價'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='原價'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(default=None, null=True, upload_to=shop.models.path_and_rename, verbose_name='主要圖片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=127, verbose_name='標題'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立於')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新於')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='特價')),
                ('status', models.CharField(blank=True, max_length=63, null=True, verbose_name='訂單狀態')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='客戶')),
            ],
        ),
    ]
