# Generated by Django 3.2.7 on 2021-10-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_mapping_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='總價'),
        ),
    ]
