# Generated by Django 3.2.7 on 2021-10-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211011_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
    ]
