# Generated by Django 3.2.7 on 2021-10-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='shop.Product', verbose_name='訂單內容'),
        ),
    ]
