# Generated by Django 3.2.7 on 2021-10-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contactform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': '聯絡表單', 'verbose_name_plural': '聯絡表單'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '使用者檔案', 'verbose_name_plural': '使用者檔案'},
        ),
    ]
